---
- name: Install Chocolatey if not present
  win_shell: |
    if (-Not (Get-Command choco -ErrorAction SilentlyContinue)) {
      Set-ExecutionPolicy Bypass -Scope Process -Force;
      [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
    }
  args:
    creates: C:\ProgramData\chocolatey\bin\choco.exe