---
- name: Install Git
  win_chocolatey:
    name: git
    state: present
  environment:
    ChocolateyInstall: C:\ProgramData\chocolatey

- name: Check if Git Duet is already installed
  win_stat:
    path: C:\Programs\Dev\GitDuet\git-duet.exe
  register: git_duet_installed

- name: Ensure C:\\Temp directory exists
  win_file:
    path: "C:\\Temp"
    state: directory
    
- name: Download Git Duet
  win_get_url:
    url: https://github.com/git-duet/git-duet/releases/download/0.10.0/windows_amd64.tar.gz
    dest: C:\temp\windows_amd64.tar.gz
  when: not git_duet_installed.stat.exists

- name: Ensure GitDuet directory exists
  win_file:
    path: "{{ install_dev_dir }}\\GitDuet"
    state: directory
  when: not git_duet_installed.stat.exists

- name: Extract Git Duet
  win_shell: |
    tar -xzf C:\temp\windows_amd64.tar.gz -C {{ install_dev_dir }}\GitDuet
  args:
    executable: powershell.exe
  when: not git_duet_installed.stat.exists
  
- name: Append Git Duet to PATH
  win_environment:
    state: present
    name: PATH
    value: >-
      {{ (lookup('env', 'PATH') + ';{{ install_dev_dir }}\GitDuet') if lookup('env', 'PATH') else '{{ install_dev_dir }}\GitDuet' }}
    level: user
  when: not git_duet_installed.stat.exists
