---
- name: Install Chocolatey if not present
  import_tasks: choco.yml

- name: Install 7-Zip under
  import_tasks: sevenzip.yml

- name: Install Firefox
  import_tasks: firefox.yml

- name: Install Git
  import_tasks: git.yml

- name: Install Notepad++
  import_tasks: notepadpp.yml  

- name: Install Putty
  import_tasks: putty.yml  

- name: Install TCPView
  import_tasks: tcpview.yml  