---
- name: Verify muCommander installation
  win_stat:
    path: "{{ install_tools_dir }}\\muCommander\\muCommander.exe"
  register: mucommander_exe
  
- name: Download muCommander installer
  win_get_url:
    url: https://github.com/mucommander/mucommander/releases/download/{{ mucommander_dir_ver }}/mucommander-{{ mucommander_ver }}.msi
    dest: "C:\\Temp\\mucommander-{{ mucommander_ver }}.msi"
  when: not mucommander_exe.stat.exists

- name: Install muCommander
  win_package:
    path: "C:\\Temp\\mucommander-{{ mucommander_ver }}.msi"
    product_id: muCommander
    arguments: '/quiet /norestart INSTALLDIR="{{ install_tools_dir }}\\muCommander"'
  when: not mucommander_exe.stat.exists

