---
- name: Download muCommander installer
  win_get_url:
    url: https://github.com/mucommander/mucommander/releases/download/1.5.0-1/mucommander-1.5.0.msi
    dest: "C:\\Temp\\mucommander-1.5.0.msi"

- name: Install muCommander
  win_package:
    path: "C:\\Temp\\mucommander-1.5.0.msi"
    product_id: muCommander
    arguments: '/quiet /norestart INSTALLDIR="{{ install_tools_dir }}\\muCommander"'
  register: mucommander_install

- name: Ensure muCommander is installed
  win_feature:
    name: "{{ mucommander_install.product_id }}"
    state: present
