---
- name: Install Notepad++
  win_chocolatey:
    name: notepadplusplus
    state: present
    install_args: '-y --install-directory={{ install_tools_dir }}\NotepadPlusPlus'
  environment:
    ChocolateyInstall: C:\ProgramData\chocolatey