---
- name: Install 7-Zip under C:\Programs\Tools\7Zip
  win_chocolatey:
    name: 7zip.install
    state: present
    install_args: '/D=C:\Programs\Tools\7Zip'
  environment:
    ChocolateyInstall: C:\ProgramData\chocolatey