---
- name: Install Apache as a service
  win_shell: |
    {{ install_net_dir }}\Apache24\bin\httpd.exe -k install
  args:
    creates: "{{ install_net_dir }}\\Apache24\\logs\\httpd.pid"
  when: not apache_installed.stat.exists

- name: Start Apache service
  win_service:
    name: Apache2.4
    start_mode: auto
    state: started