---
- name: Ensure data directory exists
  win_file:
    path: "{{ postgresql_data_path }}"
    state: directory

- name: Check if data directory is empty
  win_find:
    paths: "{{ postgresql_data_path }}"
    recurse: no
  register: pg_data_path_contents

- name: Adjust ownership of the data directory to Admin
  win_acl:
    path: "{{ postgresql_data_path }}"
    user: "Administrator"
    rights: fullcontrol
    type: allow
    state: present
  when: pg_data_path_contents.matched == 0

- name: Initialize database cluster if data directory is empty
  win_command: >
    {{ postgres_dir }}\\pgsql\\bin\\initdb.exe -D {{ postgresql_data_path }} -U postgres --locale="en_US.UTF-8"
  when: pg_data_path_contents.matched == 0

- name: Configure PostgreSQL to use new data directory
  win_template:
    src: pg_hba.conf.j2
    dest: "{{ postgresql_data_path }}\\pg_hba.conf"


- name: Adjust ownership of the data directory
  win_acl:
    path: "{{ postgresql_data_path }}"
    user: "NT AUTHORITY\\NETWORK SERVICE"
    rights: fullcontrol
    type: allow
    state: present

- name: Register PostgreSQL service
  win_service:
    name: postgresql
    path: "{{ postgres_dir }}\\pgsql\\bin\\pg_ctl.exe runservice -N postgresql -D "{{ postgresql_data_path }}" -w"
    username: "NT AUTHORITY\NetworkService"
    start_mode: auto

- name: Start PostgreSQL service
  win_service:
    name: postgresql
    state: started
