---
- name: Ensure PostgreSQL install directory exists
  win_file:
    path: "C:\\Program\\Db\\pgsql"
    state: directory

- name: Unzip PostgreSQL binaries
  win_unzip:
    src: "{{ postgres_download_url }}"
    dest: "C:\\Program\\Db"
  register: unzip_result

- name: Debug unzip result
  debug:
    var: unzip_result
