---
- name: Ensure PostgreSQL install directory exists
  win_file:
    path: "{{ postgres_dir }}\\pgsql"
    state: directory

- name: Unzip PostgreSQL binaries
  win_unzip:
    src: "{{ postgres_download_url }}"
    dest: "{{ postgres_dir }}"
  register: unzip_result

- name: Debug unzip result
  debug:
    var: unzip_result
