---
- name: Ensure PostgreSQL install directory exists
  win_file:
    path: "{{ postgres_dir }}\\pgsql"
    state: directory

- name: Unzip PostgreSQL binaries
  win_unzip:
    src: "{{ postgres_download_url }}"
    dest: "{{ postgres_dir }}"
  register: unzip_result

- name: Debug unzip result
  debug:
    var: unzip_result

- name: Adjust ownership of the data directory
  win_acl:
    path: "{{ postgres_dir }}\\pgsql"
    user: "NT AUTHORITY\\NETWORK SERVICE"
    rights: fullcontrol
    type: allow
    state: present
