postgresql_version: "16.3"
postgres_download_url: "D:\\Install\\postgresql-16.3-2-windows-x64-binaries.zip"
postgres_dir: "C:\\Programs\\Db" 
postgresql_data_path: "D:\\PgData"
log_rotation_days: 10
postgres_user: postgres